/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CondominiumCreateDto,
  CondominiumDtoIEnumerableResponseDto,
  CondominiumDtoResponseDto,
} from '../models/index';
import {
    CondominiumCreateDtoFromJSON,
    CondominiumCreateDtoToJSON,
    CondominiumDtoIEnumerableResponseDtoFromJSON,
    CondominiumDtoIEnumerableResponseDtoToJSON,
    CondominiumDtoResponseDtoFromJSON,
    CondominiumDtoResponseDtoToJSON,
} from '../models/index';

export interface ApiCondominiumAdminUserIdGetRequest {
    userId: string;
}

export interface ApiCondominiumIdDeleteRequest {
    id: number;
}

export interface ApiCondominiumIdGetRequest {
    id: number;
}

export interface ApiCondominiumPostRequest {
    condominiumCreateDto?: CondominiumCreateDto;
}

/**
 * 
 */
export class CondominiumApi extends runtime.BaseAPI {

    /**
     */
    async apiCondominiumAdminUserIdGetRaw(requestParameters: ApiCondominiumAdminUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CondominiumDtoIEnumerableResponseDto>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiCondominiumAdminUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Condominium/admin/{userId}`.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CondominiumDtoIEnumerableResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiCondominiumAdminUserIdGet(requestParameters: ApiCondominiumAdminUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CondominiumDtoIEnumerableResponseDto> {
        const response = await this.apiCondominiumAdminUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCondominiumIdDeleteRaw(requestParameters: ApiCondominiumIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCondominiumIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Condominium/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCondominiumIdDelete(requestParameters: ApiCondominiumIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCondominiumIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCondominiumIdGetRaw(requestParameters: ApiCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Condominium/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCondominiumIdGet(requestParameters: ApiCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCondominiumIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCondominiumPostRaw(requestParameters: ApiCondominiumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CondominiumDtoResponseDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/Condominium`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CondominiumCreateDtoToJSON(requestParameters['condominiumCreateDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CondominiumDtoResponseDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiCondominiumPost(requestParameters: ApiCondominiumPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CondominiumDtoResponseDto> {
        const response = await this.apiCondominiumPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
