/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSpan } from './TimeSpan';
import {
    TimeSpanFromJSON,
    TimeSpanFromJSONTyped,
    TimeSpanToJSON,
} from './TimeSpan';
import type { Reservation } from './Reservation';
import {
    ReservationFromJSON,
    ReservationFromJSONTyped,
    ReservationToJSON,
} from './Reservation';
import type { Condominium } from './Condominium';
import {
    CondominiumFromJSON,
    CondominiumFromJSONTyped,
    CondominiumToJSON,
} from './Condominium';

/**
 * 
 * @export
 * @interface CommonArea
 */
export interface CommonArea {
    /**
     * 
     * @type {number}
     * @memberof CommonArea
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonArea
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommonArea
     */
    capacity?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonArea
     */
    costPerHour?: number;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CommonArea
     */
    availableFrom?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CommonArea
     */
    availableUntil?: TimeSpan;
    /**
     * 
     * @type {number}
     * @memberof CommonArea
     */
    condominiumId?: number;
    /**
     * 
     * @type {Condominium}
     * @memberof CommonArea
     */
    condominium?: Condominium;
    /**
     * 
     * @type {Array<Reservation>}
     * @memberof CommonArea
     */
    reservations?: Array<Reservation> | null;
}

/**
 * Check if a given object implements the CommonArea interface.
 */
export function instanceOfCommonArea(value: object): value is CommonArea {
    return true;
}

export function CommonAreaFromJSON(json: any): CommonArea {
    return CommonAreaFromJSONTyped(json, false);
}

export function CommonAreaFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonArea {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'costPerHour': json['costPerHour'] == null ? undefined : json['costPerHour'],
        'availableFrom': json['availableFrom'] == null ? undefined : TimeSpanFromJSON(json['availableFrom']),
        'availableUntil': json['availableUntil'] == null ? undefined : TimeSpanFromJSON(json['availableUntil']),
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'condominium': json['condominium'] == null ? undefined : CondominiumFromJSON(json['condominium']),
        'reservations': json['reservations'] == null ? undefined : ((json['reservations'] as Array<any>).map(ReservationFromJSON)),
    };
}

export function CommonAreaToJSON(value?: CommonArea | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'capacity': value['capacity'],
        'costPerHour': value['costPerHour'],
        'availableFrom': TimeSpanToJSON(value['availableFrom']),
        'availableUntil': TimeSpanToJSON(value['availableUntil']),
        'condominiumId': value['condominiumId'],
        'condominium': CondominiumToJSON(value['condominium']),
        'reservations': value['reservations'] == null ? undefined : ((value['reservations'] as Array<any>).map(ReservationToJSON)),
    };
}

