/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSpan } from './TimeSpan';
import {
    TimeSpanFromJSON,
    TimeSpanFromJSONTyped,
    TimeSpanToJSON,
} from './TimeSpan';
import type { Reservation } from './Reservation';
import {
    ReservationFromJSON,
    ReservationFromJSONTyped,
    ReservationToJSON,
} from './Reservation';
import type { CondominiumDto } from './CondominiumDto';
import {
    CondominiumDtoFromJSON,
    CondominiumDtoFromJSONTyped,
    CondominiumDtoToJSON,
} from './CondominiumDto';

/**
 * 
 * @export
 * @interface CommonAreaDto
 */
export interface CommonAreaDto {
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    capacity?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    costPerHour?: number;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CommonAreaDto
     */
    availableFrom?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CommonAreaDto
     */
    availableUntil?: TimeSpan;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    condominiumId?: number;
    /**
     * 
     * @type {CondominiumDto}
     * @memberof CommonAreaDto
     */
    condominium?: CondominiumDto;
    /**
     * 
     * @type {Array<Reservation>}
     * @memberof CommonAreaDto
     */
    reservations?: Array<Reservation> | null;
}

/**
 * Check if a given object implements the CommonAreaDto interface.
 */
export function instanceOfCommonAreaDto(value: object): value is CommonAreaDto {
    return true;
}

export function CommonAreaDtoFromJSON(json: any): CommonAreaDto {
    return CommonAreaDtoFromJSONTyped(json, false);
}

export function CommonAreaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonAreaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'costPerHour': json['costPerHour'] == null ? undefined : json['costPerHour'],
        'availableFrom': json['availableFrom'] == null ? undefined : TimeSpanFromJSON(json['availableFrom']),
        'availableUntil': json['availableUntil'] == null ? undefined : TimeSpanFromJSON(json['availableUntil']),
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'condominium': json['condominium'] == null ? undefined : CondominiumDtoFromJSON(json['condominium']),
        'reservations': json['reservations'] == null ? undefined : ((json['reservations'] as Array<any>).map(ReservationFromJSON)),
    };
}

export function CommonAreaDtoToJSON(value?: CommonAreaDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'capacity': value['capacity'],
        'costPerHour': value['costPerHour'],
        'availableFrom': TimeSpanToJSON(value['availableFrom']),
        'availableUntil': TimeSpanToJSON(value['availableUntil']),
        'condominiumId': value['condominiumId'],
        'condominium': CondominiumDtoToJSON(value['condominium']),
        'reservations': value['reservations'] == null ? undefined : ((value['reservations'] as Array<any>).map(ReservationToJSON)),
    };
}

