/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CondominiumCreateDto
 */
export interface CondominiumCreateDto {
    /**
     * 
     * @type {string}
     * @memberof CondominiumCreateDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CondominiumCreateDto
     */
    address?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CondominiumCreateDto
     */
    numberOfResidences?: number;
    /**
     * 
     * @type {string}
     * @memberof CondominiumCreateDto
     */
    idAdministrator?: string | null;
}

/**
 * Check if a given object implements the CondominiumCreateDto interface.
 */
export function instanceOfCondominiumCreateDto(value: object): value is CondominiumCreateDto {
    return true;
}

export function CondominiumCreateDtoFromJSON(json: any): CondominiumCreateDto {
    return CondominiumCreateDtoFromJSONTyped(json, false);
}

export function CondominiumCreateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CondominiumCreateDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'address': json['address'] == null ? undefined : json['address'],
        'numberOfResidences': json['numberOfResidences'] == null ? undefined : json['numberOfResidences'],
        'idAdministrator': json['idAdministrator'] == null ? undefined : json['idAdministrator'],
    };
}

export function CondominiumCreateDtoToJSON(value?: CondominiumCreateDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'address': value['address'],
        'numberOfResidences': value['numberOfResidences'],
        'idAdministrator': value['idAdministrator'],
    };
}

