/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpStatusCode } from './HttpStatusCode';
import {
    HttpStatusCodeFromJSON,
    HttpStatusCodeFromJSONTyped,
    HttpStatusCodeToJSON,
} from './HttpStatusCode';
import type { CondominiumDto } from './CondominiumDto';
import {
    CondominiumDtoFromJSON,
    CondominiumDtoFromJSONTyped,
    CondominiumDtoToJSON,
} from './CondominiumDto';

/**
 * 
 * @export
 * @interface CondominiumDtoResponseDto
 */
export interface CondominiumDtoResponseDto {
    /**
     * 
     * @type {HttpStatusCode}
     * @memberof CondominiumDtoResponseDto
     */
    statusCode?: HttpStatusCode;
    /**
     * 
     * @type {boolean}
     * @memberof CondominiumDtoResponseDto
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CondominiumDtoResponseDto
     */
    message?: string | null;
    /**
     * 
     * @type {CondominiumDto}
     * @memberof CondominiumDtoResponseDto
     */
    data?: CondominiumDto;
}



/**
 * Check if a given object implements the CondominiumDtoResponseDto interface.
 */
export function instanceOfCondominiumDtoResponseDto(value: object): value is CondominiumDtoResponseDto {
    return true;
}

export function CondominiumDtoResponseDtoFromJSON(json: any): CondominiumDtoResponseDto {
    return CondominiumDtoResponseDtoFromJSONTyped(json, false);
}

export function CondominiumDtoResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CondominiumDtoResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : HttpStatusCodeFromJSON(json['statusCode']),
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : CondominiumDtoFromJSON(json['data']),
    };
}

export function CondominiumDtoResponseDtoToJSON(value?: CondominiumDtoResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': HttpStatusCodeToJSON(value['statusCode']),
        'success': value['success'],
        'message': value['message'],
        'data': CondominiumDtoToJSON(value['data']),
    };
}

