/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpStatusCode } from './HttpStatusCode';
import {
    HttpStatusCodeFromJSON,
    HttpStatusCodeFromJSONTyped,
    HttpStatusCodeToJSON,
} from './HttpStatusCode';
import type { CondominiumDto } from './CondominiumDto';
import {
    CondominiumDtoFromJSON,
    CondominiumDtoFromJSONTyped,
    CondominiumDtoToJSON,
} from './CondominiumDto';

/**
 * 
 * @export
 * @interface CondominiumDtoIEnumerableResponseDto
 */
export interface CondominiumDtoIEnumerableResponseDto {
    /**
     * 
     * @type {HttpStatusCode}
     * @memberof CondominiumDtoIEnumerableResponseDto
     */
    statusCode?: HttpStatusCode;
    /**
     * 
     * @type {boolean}
     * @memberof CondominiumDtoIEnumerableResponseDto
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof CondominiumDtoIEnumerableResponseDto
     */
    message?: string | null;
    /**
     * 
     * @type {Array<CondominiumDto>}
     * @memberof CondominiumDtoIEnumerableResponseDto
     */
    data?: Array<CondominiumDto> | null;
}



/**
 * Check if a given object implements the CondominiumDtoIEnumerableResponseDto interface.
 */
export function instanceOfCondominiumDtoIEnumerableResponseDto(value: object): value is CondominiumDtoIEnumerableResponseDto {
    return true;
}

export function CondominiumDtoIEnumerableResponseDtoFromJSON(json: any): CondominiumDtoIEnumerableResponseDto {
    return CondominiumDtoIEnumerableResponseDtoFromJSONTyped(json, false);
}

export function CondominiumDtoIEnumerableResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CondominiumDtoIEnumerableResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : HttpStatusCodeFromJSON(json['statusCode']),
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(CondominiumDtoFromJSON)),
    };
}

export function CondominiumDtoIEnumerableResponseDtoToJSON(value?: CondominiumDtoIEnumerableResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': HttpStatusCodeToJSON(value['statusCode']),
        'success': value['success'],
        'message': value['message'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(CondominiumDtoToJSON)),
    };
}

