/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSpan } from './TimeSpan';
import {
    TimeSpanFromJSON,
    TimeSpanFromJSONTyped,
    TimeSpanToJSON,
} from './TimeSpan';

/**
 * 
 * @export
 * @interface CreateCommonAreaDto
 */
export interface CreateCommonAreaDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCommonAreaDto
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateCommonAreaDto
     */
    capacity?: number;
    /**
     * 
     * @type {number}
     * @memberof CreateCommonAreaDto
     */
    costPerHour?: number;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CreateCommonAreaDto
     */
    availableFrom?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof CreateCommonAreaDto
     */
    availableUntil?: TimeSpan;
    /**
     * 
     * @type {number}
     * @memberof CreateCommonAreaDto
     */
    condominiumId?: number;
}

/**
 * Check if a given object implements the CreateCommonAreaDto interface.
 */
export function instanceOfCreateCommonAreaDto(value: object): value is CreateCommonAreaDto {
    return true;
}

export function CreateCommonAreaDtoFromJSON(json: any): CreateCommonAreaDto {
    return CreateCommonAreaDtoFromJSONTyped(json, false);
}

export function CreateCommonAreaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCommonAreaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'costPerHour': json['costPerHour'] == null ? undefined : json['costPerHour'],
        'availableFrom': json['availableFrom'] == null ? undefined : TimeSpanFromJSON(json['availableFrom']),
        'availableUntil': json['availableUntil'] == null ? undefined : TimeSpanFromJSON(json['availableUntil']),
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
    };
}

export function CreateCommonAreaDtoToJSON(value?: CreateCommonAreaDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'capacity': value['capacity'],
        'costPerHour': value['costPerHour'],
        'availableFrom': TimeSpanToJSON(value['availableFrom']),
        'availableUntil': TimeSpanToJSON(value['availableUntil']),
        'condominiumId': value['condominiumId'],
    };
}

