/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { HttpStatusCode } from './HttpStatusCode';
import {
    HttpStatusCodeFromJSON,
    HttpStatusCodeFromJSONTyped,
    HttpStatusCodeToJSON,
} from './HttpStatusCode';
import type { LoginResponseDto } from './LoginResponseDto';
import {
    LoginResponseDtoFromJSON,
    LoginResponseDtoFromJSONTyped,
    LoginResponseDtoToJSON,
} from './LoginResponseDto';

/**
 * 
 * @export
 * @interface LoginResponseDtoResponseDto
 */
export interface LoginResponseDtoResponseDto {
    /**
     * 
     * @type {HttpStatusCode}
     * @memberof LoginResponseDtoResponseDto
     */
    statusCode?: HttpStatusCode;
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseDtoResponseDto
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseDtoResponseDto
     */
    message?: string | null;
    /**
     * 
     * @type {LoginResponseDto}
     * @memberof LoginResponseDtoResponseDto
     */
    data?: LoginResponseDto;
}



/**
 * Check if a given object implements the LoginResponseDtoResponseDto interface.
 */
export function instanceOfLoginResponseDtoResponseDto(value: object): value is LoginResponseDtoResponseDto {
    return true;
}

export function LoginResponseDtoResponseDtoFromJSON(json: any): LoginResponseDtoResponseDto {
    return LoginResponseDtoResponseDtoFromJSONTyped(json, false);
}

export function LoginResponseDtoResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseDtoResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'statusCode': json['statusCode'] == null ? undefined : HttpStatusCodeFromJSON(json['statusCode']),
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : LoginResponseDtoFromJSON(json['data']),
    };
}

export function LoginResponseDtoResponseDtoToJSON(value?: LoginResponseDtoResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'statusCode': HttpStatusCodeToJSON(value['statusCode']),
        'success': value['success'],
        'message': value['message'],
        'data': LoginResponseDtoToJSON(value['data']),
    };
}

