/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSpan } from './TimeSpan';
import {
    TimeSpanFromJSON,
    TimeSpanFromJSONTyped,
    TimeSpanToJSON,
} from './TimeSpan';
import type { CommonAreaDto } from './CommonAreaDto';
import {
    CommonAreaDtoFromJSON,
    CommonAreaDtoFromJSONTyped,
    CommonAreaDtoToJSON,
} from './CommonAreaDto';

/**
 * 
 * @export
 * @interface ReservationDto
 */
export interface ReservationDto {
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    readonly id?: number;
    /**
     * 
     * @type {Date}
     * @memberof ReservationDto
     */
    readonly reservationDate?: Date;
    /**
     * 
     * @type {TimeSpan}
     * @memberof ReservationDto
     */
    startTime?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof ReservationDto
     */
    endTime?: TimeSpan;
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    readonly totalCost?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    readonly commonAreaId?: number;
    /**
     * 
     * @type {CommonAreaDto}
     * @memberof ReservationDto
     */
    commonArea?: CommonAreaDto;
    /**
     * 
     * @type {string}
     * @memberof ReservationDto
     */
    readonly userId?: string | null;
}

/**
 * Check if a given object implements the ReservationDto interface.
 */
export function instanceOfReservationDto(value: object): value is ReservationDto {
    return true;
}

export function ReservationDtoFromJSON(json: any): ReservationDto {
    return ReservationDtoFromJSONTyped(json, false);
}

export function ReservationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reservationDate': json['reservationDate'] == null ? undefined : (new Date(json['reservationDate'])),
        'startTime': json['startTime'] == null ? undefined : TimeSpanFromJSON(json['startTime']),
        'endTime': json['endTime'] == null ? undefined : TimeSpanFromJSON(json['endTime']),
        'totalCost': json['totalCost'] == null ? undefined : json['totalCost'],
        'commonAreaId': json['commonAreaId'] == null ? undefined : json['commonAreaId'],
        'commonArea': json['commonArea'] == null ? undefined : CommonAreaDtoFromJSON(json['commonArea']),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ReservationDtoToJSON(value?: Omit<ReservationDto, 'id'|'reservationDate'|'totalCost'|'commonAreaId'|'userId'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'startTime': TimeSpanToJSON(value['startTime']),
        'endTime': TimeSpanToJSON(value['endTime']),
        'commonArea': CommonAreaDtoToJSON(value['commonArea']),
    };
}

