/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ReservationDto } from './ReservationDto';
import {
    ReservationDtoFromJSON,
    ReservationDtoFromJSONTyped,
    ReservationDtoToJSON,
} from './ReservationDto';

/**
 * 
 * @export
 * @interface ReservationDtoResponseDto
 */
export interface ReservationDtoResponseDto {
    /**
     * 
     * @type {boolean}
     * @memberof ReservationDtoResponseDto
     */
    success?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ReservationDtoResponseDto
     */
    message?: string | null;
    /**
     * 
     * @type {ReservationDto}
     * @memberof ReservationDtoResponseDto
     */
    data?: ReservationDto;
}

/**
 * Check if a given object implements the ReservationDtoResponseDto interface.
 */
export function instanceOfReservationDtoResponseDto(value: object): value is ReservationDtoResponseDto {
    return true;
}

export function ReservationDtoResponseDtoFromJSON(json: any): ReservationDtoResponseDto {
    return ReservationDtoResponseDtoFromJSONTyped(json, false);
}

export function ReservationDtoResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationDtoResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'message': json['message'] == null ? undefined : json['message'],
        'data': json['data'] == null ? undefined : ReservationDtoFromJSON(json['data']),
    };
}

export function ReservationDtoResponseDtoToJSON(value?: ReservationDtoResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'message': value['message'],
        'data': ReservationDtoToJSON(value['data']),
    };
}

