/* tslint:disable */
/* eslint-disable */
/**
 * CondoPlanner API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TimeSpan } from './TimeSpan';
import {
    TimeSpanFromJSON,
    TimeSpanFromJSONTyped,
    TimeSpanToJSON,
} from './TimeSpan';
import type { CommonArea } from './CommonArea';
import {
    CommonAreaFromJSON,
    CommonAreaFromJSONTyped,
    CommonAreaToJSON,
} from './CommonArea';

/**
 * 
 * @export
 * @interface Reservation
 */
export interface Reservation {
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    id?: number;
    /**
     * 
     * @type {Date}
     * @memberof Reservation
     */
    reservationDate?: Date;
    /**
     * 
     * @type {TimeSpan}
     * @memberof Reservation
     */
    startTime?: TimeSpan;
    /**
     * 
     * @type {TimeSpan}
     * @memberof Reservation
     */
    endTime?: TimeSpan;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    totalCost?: number;
    /**
     * 
     * @type {number}
     * @memberof Reservation
     */
    commonAreaId?: number;
    /**
     * 
     * @type {CommonArea}
     * @memberof Reservation
     */
    commonArea?: CommonArea;
    /**
     * 
     * @type {string}
     * @memberof Reservation
     */
    userId?: string | null;
}

/**
 * Check if a given object implements the Reservation interface.
 */
export function instanceOfReservation(value: object): value is Reservation {
    return true;
}

export function ReservationFromJSON(json: any): Reservation {
    return ReservationFromJSONTyped(json, false);
}

export function ReservationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Reservation {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'reservationDate': json['reservationDate'] == null ? undefined : (new Date(json['reservationDate'])),
        'startTime': json['startTime'] == null ? undefined : TimeSpanFromJSON(json['startTime']),
        'endTime': json['endTime'] == null ? undefined : TimeSpanFromJSON(json['endTime']),
        'totalCost': json['totalCost'] == null ? undefined : json['totalCost'],
        'commonAreaId': json['commonAreaId'] == null ? undefined : json['commonAreaId'],
        'commonArea': json['commonArea'] == null ? undefined : CommonAreaFromJSON(json['commonArea']),
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ReservationToJSON(value?: Reservation | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'reservationDate': value['reservationDate'] == null ? undefined : ((value['reservationDate']).toISOString()),
        'startTime': TimeSpanToJSON(value['startTime']),
        'endTime': TimeSpanToJSON(value['endTime']),
        'totalCost': value['totalCost'],
        'commonAreaId': value['commonAreaId'],
        'commonArea': CommonAreaToJSON(value['commonArea']),
        'userId': value['userId'],
    };
}

